### ISSUE TITLE
Thamos config causing issues on builds.

### ISSUE THREAD

**Issue by harshad16** [thoth-station/s2i-minimal-notebook#97] opened 2021-09-28 13:59 UTC
**Describe the bug**

While trying to use the s2i-minimal-notebook as a base image. users are facing issues if they don't have `.thoth.yaml` in the repo
```
2021-09-27 19:56:45,047 [12] ERROR    thamos.config: Schema validation failed: please make sure you run Thamos which supports the supplied configuration file
2021-09-27 19:56:45,050 [12] CRITICAL root: Traceback (most recent call last):
  File "/opt/app-root/bin/thamos", line 8, in <module>
    sys.exit(cli())
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/cli.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/cli.py", line 1074, in check
    result = configuration.check(runtime_environment_name=runtime_environment)
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/config.py", line 613, in check
    self.check_schema()
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/config.py", line 655, in check_schema
    validate(instance=self.content, schema=_CONFIG_SCHEMA)
  File "/opt/app-root/lib64/python3.8/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: 'host' is a required property
```
Threadlink: https://chat.google.com/room/AAAAVjnVXFk/tpHdY_5kQSY

**Comment by Gkrumbach07** [comment] 2022-10-07 16:25
closing this issue as in my opinion it is not a bug but a lack of documentation of how to use the base image. Docs are updated. Reopen issue if you think there is something else that needs to be changed

/close

**Closed by Gkrumbach07** 2022-10-07 16:25 UTC
Labels: human_intervention_required, kind/bug, sig/user-experience, lifecycle/frozen, triage/accepted
